[package]
name = "pubster"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
tokio = "1.45.0"
tonic = "0.13.1"

[build-dependencies]
tonic-build = "0.13.1"

[[bin]]
name = "server"
path = "src/server/bin/main.rs"


[[bin]]
name = "client"
path = "src/client/bin/main.rs"
